### ISSUE TITLE
Unable to make

### ISSUE THREAD

**Issue by beliboba** [artyom-poptsov/SPARC#1]
Beliboba@BLBB MINGW64 ~/SPARC (master)
$ make
GEN out/sections/commands.tex
make: *** [makefile:61: out/sections/commands.tex] Error 127

**Comment by artyom-poptsov** [comment]
Have you installed all the dependencies as described in the `README`?

**Comment by beliboba** [comment]
Unable to install anything but miktex since im using windows. 
Trying to setup wsl
