### ISSUE TITLE
Орфография (3.1)

### ISSUE THREAD

**Issue by V4n0M4sk** [artyom-poptsov/SPARC#3]
...компьютер или микроконтроллер может получать самую различную информацию...
Некорректное употребление степени превосходства
самую РАЗНУЮ
или
РАЗЛИЧНУЮ

Самую различную - некорректно

3.2.4. 
- Чтение чисел

Давайте напишем маленькую эхо-программу, которая покажет принцип работы
данной функции и позволит вам узнать(,) какому символу соответствует то или иное
число.

В скобках указана пропущенная запятая.

Там же:
{} - было
() - стало

Если в мониторе порта вы введете строку “72”(,) то монитор порта отправит его на Arduino как два байта данных в виде
чисел 55 и 51, функция Serial.parseInt подождет 2000 миллисекунд (как
видите(,) я (мы) поменял время ожиданиЯ с 1 секунды на 2 секунды, чтобы нагляднее
показать кое(-)какие аспекты)(,) увидит эти два значения(,) {и} преобразует их в одно
целочисленное 72 и присвоит его переменной incoming_int(.) {,} Мы с помощью
метода Serial.write передадим число 72 как есть обратно в монитор порта
(почему именно этот метод нужен читайте далее)(,) где монитор порта корректно
преобразует число 72 в соответствующий символ и покажет нам символ “H”(,) который соответствует коду 72.

Там же:

Таким образом(,) мы можем передавать числовые значения с компьютера на платформу Arduino и дальше использовать эти значения.

**Comment by artyom-poptsov** [comment]
Исправил в cd1183d
