### ISSUE TITLE
Орфография 3.3

### ISSUE THREAD

**Issue by V4n0M4sk** [artyom-poptsov/SPARC#4]
{} - было
() - стало

На отладочной плате Arduino присутствуют(,) так называемые аналоговые порты,
которые позволяют считывать аналоговый сигнал.

Последний абзац 3.3:

Благодаря своей непредсказуемости, он может быть использован в качестве источника случайных
чисел – что бывает полезно(:) например(,) при разработке игр, о чём будет рассказано
в последующих главах книги.

3.4 

Посмотрим на последний график: для кодирования значений используется {три} (3) бита{,}(.) Значит АЦП, описываемый таким
графиком, {имеет, соответственно,} (соответственно, имеет) разрядность 3 бита. 

4.2
Где {длина периода} (длина волны?) (время периода?) (длительность периода?) – расстояние между двумя ближайшими друг к другу точками в пространстве, в которых колебания происходят в одинаковой фазе.

То же самое:

Зная длину периода, можно рассчитать частоту колебаний, и наоборот – зная
частоту, можно рассчитать длину волны.
При работе с ШИМ мы будем использовать длину периода, заданную в микросекундах (мкс).

Технически, для упрощённого понимания, можно использовать данную конструкцию. Но, с точки зрения радиотехники, это грубая ошибка.

**Comment by artyom-poptsov** [comment]
> На отладочной плате Arduino присутствуют(,) так называемые аналоговые порты,
которые позволяют считывать аналоговый сигнал.

С этим не согласен, тут запятой не требуется.
