### ISSUE TITLE
орфография 5.2

### ISSUE THREAD

**Issue by V4n0M4sk** [artyom-poptsov/SPARC#5]
5.2

Есть несколько вариантов динамиков, которые вы можете встретить. Например,
есть обычные динамики, где мембрана колеблется (под воздействием) магнитн{ым}(ого) пол{ем}(я) и тем самым
создаёт колебания воздуха, которые мы слышим{,} как звук. {Есть}(Существуют?)(Также, существуют? ) пьезодинамики,
в которых звук генерируется за счёт обратного пьезоэлектрического эффекта –
механической деформации пьезоэлектрика под действием электрического поля.

5.2.1

Однако, если мы хотим сгенерировать что-нибудь интересное {–}(,) вроде мелодии {–}(,) то нам
потребуется использовать ((вполне) - лишнее уточнение) определённые частоты. {Здесь нам очень кстати
будет хотя бы} (В данном случае желательным будет...) начальное знание музыкальной теории, но если {таких знаний} (такового) нет – не беда, разберём(ся) по ходу дела.

5.3

Думаю, большинство из нас представляют, что такое ритм – у многих именно он вызывает,
например рефлекс покачивания головой в такт или машинальное отстукивание
ритма на столешниц{а}(е) {стола}, когда думаем над чем-то.

5.3.2

Частоты звуков мы (,) опять же (,) берём произвольно.

Как мы видим{о} из рисунка 5.3.3, деление такта на части не обязательно должно быть всегда равномерным – здесь мы получили две четверти{,} и одну половину.

Суммарно же(,) у нас {опять} выходит единица |(см. формулу 5.3.) | (.) Попутно вспоминаем, что для сложения простых дробей нам необходимо их привести к общему знаменателю.

5.3.3

...записываются слева на{}право, как и обычный, привычный нам русский текст... 

5.3.4

Из-за этого в оригинале композиция кажется в два раза быстрее – не потому, что там выше BPM, а {просто по тому, что}(из-за того, что) сами ноты...

**Comment by artyom-poptsov** [comment]
5.2 и 5.2.1 исправил в 8fb1d51

**Comment by artyom-poptsov** [comment]
Остальное исправил в [de84335](https://github.com/artyom-poptsov/SPARC/commit/de8433542b0835b7788c792357c611f2675c77e0)
