### ISSUE TITLE
Орфография (Том 4) 

### ISSUE THREAD

**Issue by V4n0M4sk** [artyom-poptsov/SPARC#6]
5.10

Здесь стоит упомянуть, что в музыке встречаются ноты (с) двумя точками справа, что даёт удлинение ноты на половину её длительности и на половину от половины – но подобные ситуации редки из-за неудобства расчёта необходимой длительности при чтении музыкантом нот с листа.

5.11

{Для того, чтобы например} (Например, чтобы )получить частоту клавиши между парой “C”–“D”, можно поднять частоту “C” на пол{-}тона, либо понизить частоту “D” на те же пол{-}тона.
Модификатор, повышающий частоту ноты на пол{-}тона называется диезом, тогда как аналогичный модификатор, понижающий частоту на пол{-}тона, называется бемолем.

5.12

Второй {,}(-) второстепенный акцент {,}(-) ставится на третью ноту в такте, или же(,) можно сказать, {что} на первую
ноту второй половины такта (относительно сильную долю{|.)|} (|).|)

Основной акцент (,) по определению (,) более выраженный, чем второстепенный.

Музыкальный размер “две четверти” используется в таких стилях музыки{,} как(,) например(,) полька.

5.14.2

Пусть и нашей первой композицией будет Arduino-кавер на композицию “Sweet Dreams” под авторством Marilyn Manson
(см. рис. 5.14.25{|.)|}   (|).|)12

**Comment by artyom-poptsov** [comment]
Я вообще обычно ставлю точку внутри скобок (если предложение оканчивается скобкой.)

Это просто мой стиль такой.  ;-)
